### ISSUE TITLE
still not mobile friendly

### ISSUE THREAD

**Issue by AmitAronovitch** [AmitAronovitch/pyconil2019-placeholder#16]
On mobile (Android Firefox / Android Chrome), instead of folding to narrow screen, I get the same view as in desktop, but with tiny fonts.

**Comment by boaz0** [comment]
I forgot to add this meta tag into the header the HTML:
```HTML
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by AmitAronovitch** [comment]
tks - will quickfix this.
